# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20200305_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(related_name='follows', to='insta.Profile'),
        ),
    ]
